/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DAO_Tablespace;
import MODEL.TableModelDetail_Tablespace;
import POJO.POJO_Datafile;
import POJO.POJO_Tablespace;
import POJO.POJO_User;
import SqlServerProvider.SQLConnectThrowJDBC;
import SqlServerProvider.SQLProvider;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author trung
 */
public class GUI_Moredetail_Tablespace extends javax.swing.JPanel {
    DefaultTreeModel modelTree;
    TableModelDetail_Tablespace tblModelTableSpace;
    DefaultMutableTreeNode nodeRoot;
    DefaultMutableTreeNode a;
    DefaultMutableTreeNode b;
    DefaultMutableTreeNode nodeTablespace;
    POJO_User user=new POJO_User();
    /**
     * Creates new form GUI_Moredetail_Tablespace
     */
    public GUI_Moredetail_Tablespace() {
        initComponents();
        initTabledetail();
        initTree();
        
    }
    public void initTree(){
        DefaultMutableTreeNode nodeRoot = new DefaultMutableTreeNode("Thông Tin");
            modelTree = new DefaultTreeModel(nodeRoot);
            treeTablespace.setModel(modelTree);
             a = new DefaultMutableTreeNode("Tablespace");
             b = new DefaultMutableTreeNode("Datafile");
            nodeRoot.add(a);
            nodeRoot.add(b);
            SQLConnectThrowJDBC provider =new SQLConnectThrowJDBC(); 
         try {
            
            provider.Open(user.getUsername(),user.getPassword(),user.getEnable(),user.getHost(),user.getPort(),user.getSid());
            String query="Select name from v$tablespace";
            ResultSet rs=provider.executeQuery(query);
            while (rs.next())
            {
                POJO_Tablespace tblSpace=new POJO_Tablespace();
                tblSpace.setName(rs.getString(1));
                DefaultMutableTreeNode nodeTablespace = new DefaultMutableTreeNode(tblSpace);
                a.add(nodeTablespace);    
            }
            String query1="Select name from v$datafile";
            ResultSet rs1=provider.executeQuery(query1);
            while (rs1.next())
            {
               POJO_Datafile datafile=new POJO_Datafile();
               datafile.setName(rs1.getString(1));
               DefaultMutableTreeNode nodeDatafile = new DefaultMutableTreeNode(datafile);
               b.add(nodeDatafile);
            }
            
                
        } catch (SQLException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void initTabledetail()
    {
         tblModelTableSpace= new TableModelDetail_Tablespace();
        tblDetail.setModel(tblModelTableSpace);
        tblDetail.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()){
                        return;
                }
                int index=tblDetail.getSelectedRow();
                if (index <0){
                    return ;
                }
                  POJO_Tablespace tbl=tblModelTableSpace.getByIndex(index);
                txtNametblspace.setText(tbl.getName());
                txtNameDatafile.setText(tbl.getName_datafile());
                
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        treeTablespace = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNametblspace = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNameDatafile = new javax.swing.JTextField();
        btnXoaTbl = new javax.swing.JRadioButton();
        btnXoadatafile = new javax.swing.JRadioButton();
        btnUpdateTree = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        jScrollPane8.setViewportView(treeTablespace);

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetail);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel1.setText("Name_Tablespace:");

        jLabel2.setText("Size:");

        jLabel3.setText("Name.Path_datafile:");

        btnXoaTbl.setText("Xóa Tablespace");
        btnXoaTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTblActionPerformed(evt);
            }
        });

        btnXoadatafile.setText("Xóa Datafile");
        btnXoadatafile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoadatafileActionPerformed(evt);
            }
        });

        btnUpdateTree.setText("Cập nhập lại cây");
        btnUpdateTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTreeActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateTree, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXoaTbl)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXoadatafile)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btnSearch)
                                        .addGap(31, 31, 31)
                                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNametblspace, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNameDatafile, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtNametblspace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(txtNameDatafile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaTbl)
                    .addComponent(btnXoadatafile))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateTree)
                    .addComponent(btnXoa)
                    .addComponent(btnThem)
                    .addComponent(btnSearch)
                    .addComponent(btnSua))
                .addContainerGap(306, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String name=txtNametblspace.getText();
        String path="D:\\ORACLE\\ORCL\\";
        String size=txtSize.getText();
        String namedatafile=txtNameDatafile.getText();
        POJO_Tablespace tbl =new POJO_Tablespace();
        
        
        tbl.setName(name);
        tbl.setName_datafile(path+name+".DBF");
        if (name.length()<=0 && size.length()<=0)
        {
             JOptionPane.showMessageDialog(this, "tablespace và size không được để trống");
        }
        else if (DAO_Tablespace.kiemtraNameTblspace(name)==true &&namedatafile.length()>0 )
        {
            tbl.setName_datafile(path+namedatafile+".DBF");
            DAO_Tablespace.addDatafileOnly(name,namedatafile,size);
            tblModelTableSpace.addElement(tbl);
               
        }
        else 
        {
            DAO_Tablespace.addDatafile(name, size);
            tblModelTableSpace.addElement(tbl);
            
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
           int index=tblDetail.getSelectedRow();
            if (btnXoaTbl.isSelected())
            {
                DAO_Tablespace.deleteTablespace(txtNametblspace.getText());
                tblModelTableSpace= new TableModelDetail_Tablespace();
                tblDetail.setModel(tblModelTableSpace);
            }
            else if(index<=0)
            {
                JOptionPane.showMessageDialog(this, "hãy chọn trước khi xóa");
            }
            else if (btnXoadatafile.isSelected())
            {
                DAO_Tablespace.deleteDatafile(txtNametblspace.getText(),txtNameDatafile.getText());
                POJO_Tablespace tblspace=tblModelTableSpace.getByIndex(index);
                tblModelTableSpace.removeElement(tblspace);
            }
            else 
            {
                JOptionPane.showMessageDialog(this,"Xin hãy chọn 1 trong 2 chức năng","Xác nhận",JOptionPane.INFORMATION_MESSAGE);
            }
                   
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTblActionPerformed
        // TODO add your handling code here:
        if (btnXoaTbl.isSelected())
        {
            btnXoadatafile.setSelected(false);
        }
            
    }//GEN-LAST:event_btnXoaTblActionPerformed

    private void btnXoadatafileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoadatafileActionPerformed
        // TODO add your handling code here:
        if (btnXoadatafile.isSelected())
        {
            btnXoaTbl.setSelected(false);
        }
    }//GEN-LAST:event_btnXoadatafileActionPerformed

    private void btnUpdateTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTreeActionPerformed
        // TODO add your handling code here:
        initTree();
    }//GEN-LAST:event_btnUpdateTreeActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        tblModelTableSpace= new TableModelDetail_Tablespace(txtNametblspace.getText());
                tblDetail.setModel(tblModelTableSpace);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        POJO_Tablespace tbl =new POJO_Tablespace();
        DAO_Tablespace daoTbl=new DAO_Tablespace();
        daoTbl.AlterDatafile(txtNameDatafile.getText(),txtSize.getText());
        tbl.setName(txtNametblspace.getText());
        tbl.setName_datafile(txtNameDatafile.getText());
        tbl.setBytes(txtSize.getText());
        tblModelTableSpace= new TableModelDetail_Tablespace();
        tblDetail.setModel(tblModelTableSpace);
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdateTree;
    private javax.swing.JButton btnXoa;
    private javax.swing.JRadioButton btnXoaTbl;
    private javax.swing.JRadioButton btnXoadatafile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTree treeTablespace;
    private javax.swing.JTextField txtNameDatafile;
    private javax.swing.JTextField txtNametblspace;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
