/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DAO_PGA;
import MODEL.TableModeAlertLog;
import MODEL.TableModeControlfile;
import MODEL.TableModeDictionary;
import MODEL.TableModelDatabase;
import MODEL.TableModelDatafile;
import MODEL.TableModelPGA;
import MODEL.TableModelSGA;
import MODEL.TableModelInstance;
import MODEL.TableModelLogfile;
import POJO.POJO_PGA;
import POJO.POJO_User;
import SqlServerProvider.SQLConnectThrowJDBC;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.tree.DefaultTreeModel;


/**
 *
 * @author trung
 */
public class GUI_InfoOracle extends javax.swing.JPanel {
    
    TableModelSGA tblModelSga;
    TableModelPGA tblModelPga;
    TableModelInstance tblModelInstance;
    TableModelDatabase tblModelDatabase;
    TableModeControlfile tblModelControlfile;
    TableModelDatafile tblModelDatafile;
    TableModelLogfile tblModelLogfile;
    DefaultTreeModel modelTree;
    TableModeAlertLog tblModelAlertlog;
    TableModeDictionary tblModelDictionary;
    POJO_User user=new POJO_User();
    /**
     * Creates new form GUI_InfoOracle
     */
    public GUI_InfoOracle() {
        initComponents();
        
        
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSga = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSGA1 = new javax.swing.JTable();
        dialogPga = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPga = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNamepga = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        dialogIntance = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInstance = new javax.swing.JTable();
        dialogData = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDatabase = new javax.swing.JTable();
        dialogControl = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblControlfile = new javax.swing.JTable();
        dialoDatafile = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDatafile = new javax.swing.JTable();
        dialogLogfile = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblLogfile = new javax.swing.JTable();
        diallogAlert = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblAlert = new javax.swing.JTable();
        dialogDictionary = new javax.swing.JDialog();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblDictionary = new javax.swing.JTable();
        diallogShutdown = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        btnAbort = new javax.swing.JButton();
        btnImed = new javax.swing.JButton();
        btnTrans = new javax.swing.JButton();
        btnNormal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnSystem = new javax.swing.JPanel();
        btnDatafile = new javax.swing.JButton();
        btnLogfile = new javax.swing.JButton();
        btnInstance = new javax.swing.JButton();
        btnPGA = new javax.swing.JButton();
        btnAlert1 = new javax.swing.JButton();
        btnSGA = new javax.swing.JButton();
        btnDatabase = new javax.swing.JButton();
        btnDictionary = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnShutdown = new javax.swing.JButton();
        btnControlfile = new javax.swing.JButton();
        btnStartup = new javax.swing.JButton();
        btnBak = new javax.swing.JButton();
        btnRes = new javax.swing.JButton();
        btnArchiveLg = new javax.swing.JButton();
        txtTimebak = new javax.swing.JTextField();

        dialogSga.setTitle("SGA");
        dialogSga.setLocation(new java.awt.Point(400, 400));
        dialogSga.setMinimumSize(new java.awt.Dimension(590, 220));
        dialogSga.setModal(true);

        tblSGA1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblSGA1);

        javax.swing.GroupLayout dialogSgaLayout = new javax.swing.GroupLayout(dialogSga.getContentPane());
        dialogSga.getContentPane().setLayout(dialogSgaLayout);
        dialogSgaLayout.setHorizontalGroup(
            dialogSgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSgaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        dialogSgaLayout.setVerticalGroup(
            dialogSgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSgaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        dialogPga.setTitle("PGA");
        dialogPga.setLocation(new java.awt.Point(400, 400));
        dialogPga.setMinimumSize(new java.awt.Dimension(400, 220));

        tblPga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPga);

        jLabel3.setText("NAME:");

        jLabel4.setText("VALUE:");

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogPgaLayout = new javax.swing.GroupLayout(dialogPga.getContentPane());
        dialogPga.getContentPane().setLayout(dialogPgaLayout);
        dialogPgaLayout.setHorizontalGroup(
            dialogPgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPgaLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(dialogPgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogPgaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(dialogPgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dialogPgaLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNamepga, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(265, 265, 265))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogPgaLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit)
                            .addContainerGap()))))
        );
        dialogPgaLayout.setVerticalGroup(
            dialogPgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPgaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogPgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamepga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        dialogIntance.setTitle("Instance");
        dialogIntance.setLocation(new java.awt.Point(400, 400));
        dialogIntance.setMinimumSize(new java.awt.Dimension(590, 220));

        tblInstance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblInstance);

        javax.swing.GroupLayout dialogIntanceLayout = new javax.swing.GroupLayout(dialogIntance.getContentPane());
        dialogIntance.getContentPane().setLayout(dialogIntanceLayout);
        dialogIntanceLayout.setHorizontalGroup(
            dialogIntanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogIntanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
        );
        dialogIntanceLayout.setVerticalGroup(
            dialogIntanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogIntanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        dialogData.setTitle("Database");
        dialogData.setLocation(new java.awt.Point(400, 400));
        dialogData.setMinimumSize(new java.awt.Dimension(590, 220));

        tblDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblDatabase);

        javax.swing.GroupLayout dialogDataLayout = new javax.swing.GroupLayout(dialogData.getContentPane());
        dialogData.getContentPane().setLayout(dialogDataLayout);
        dialogDataLayout.setHorizontalGroup(
            dialogDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(dialogDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogDataLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        dialogDataLayout.setVerticalGroup(
            dialogDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
            .addGroup(dialogDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogDataLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );

        dialogControl.setTitle("Controlfile");
        dialogControl.setLocation(new java.awt.Point(400, 400));
        dialogControl.setMinimumSize(new java.awt.Dimension(590, 220));

        tblControlfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblControlfile);

        javax.swing.GroupLayout dialogControlLayout = new javax.swing.GroupLayout(dialogControl.getContentPane());
        dialogControl.getContentPane().setLayout(dialogControlLayout);
        dialogControlLayout.setHorizontalGroup(
            dialogControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogControlLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        dialogControlLayout.setVerticalGroup(
            dialogControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogControlLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        dialoDatafile.setTitle("Datafille");
        dialoDatafile.setLocation(new java.awt.Point(400, 400));
        dialoDatafile.setMinimumSize(new java.awt.Dimension(590, 220));

        tblDatafile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblDatafile);

        javax.swing.GroupLayout dialoDatafileLayout = new javax.swing.GroupLayout(dialoDatafile.getContentPane());
        dialoDatafile.getContentPane().setLayout(dialoDatafileLayout);
        dialoDatafileLayout.setHorizontalGroup(
            dialoDatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialoDatafileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dialoDatafileLayout.setVerticalGroup(
            dialoDatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialoDatafileLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        dialogLogfile.setTitle("Logfile");
        dialogLogfile.setLocation(new java.awt.Point(400, 400));
        dialogLogfile.setMinimumSize(new java.awt.Dimension(590, 220));

        tblLogfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblLogfile);

        javax.swing.GroupLayout dialogLogfileLayout = new javax.swing.GroupLayout(dialogLogfile.getContentPane());
        dialogLogfile.getContentPane().setLayout(dialogLogfileLayout);
        dialogLogfileLayout.setHorizontalGroup(
            dialogLogfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogLogfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dialogLogfileLayout.setVerticalGroup(
            dialogLogfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLogfileLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        diallogAlert.setLocation(new java.awt.Point(400, 400));
        diallogAlert.setMinimumSize(new java.awt.Dimension(590, 220));

        tblAlert.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblAlert);

        javax.swing.GroupLayout diallogAlertLayout = new javax.swing.GroupLayout(diallogAlert.getContentPane());
        diallogAlert.getContentPane().setLayout(diallogAlertLayout);
        diallogAlertLayout.setHorizontalGroup(
            diallogAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        diallogAlertLayout.setVerticalGroup(
            diallogAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diallogAlertLayout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );

        dialogDictionary.setLocation(new java.awt.Point(400, 400));
        dialogDictionary.setMinimumSize(new java.awt.Dimension(590, 220));

        tblDictionary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tblDictionary);

        javax.swing.GroupLayout dialogDictionaryLayout = new javax.swing.GroupLayout(dialogDictionary.getContentPane());
        dialogDictionary.getContentPane().setLayout(dialogDictionaryLayout);
        dialogDictionaryLayout.setHorizontalGroup(
            dialogDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogDictionaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialogDictionaryLayout.setVerticalGroup(
            dialogDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDictionaryLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        diallogShutdown.setLocation(new java.awt.Point(400, 400));
        diallogShutdown.setMinimumSize(new java.awt.Dimension(590, 220));

        btnAbort.setText("Abort");
        btnAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbortActionPerformed(evt);
            }
        });

        btnImed.setText("Imediately");
        btnImed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImedActionPerformed(evt);
            }
        });

        btnTrans.setText("Transaction");
        btnTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransActionPerformed(evt);
            }
        });

        btnNormal.setText("Normal");
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });

        jLabel2.setText("Xin hãy chọn chức năng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnAbort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImed)
                .addGap(14, 14, 14)
                .addComponent(btnTrans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(135, 135, 135))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbort)
                    .addComponent(btnImed)
                    .addComponent(btnTrans)
                    .addComponent(btnNormal))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout diallogShutdownLayout = new javax.swing.GroupLayout(diallogShutdown.getContentPane());
        diallogShutdown.getContentPane().setLayout(diallogShutdownLayout);
        diallogShutdownLayout.setHorizontalGroup(
            diallogShutdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        diallogShutdownLayout.setVerticalGroup(
            diallogShutdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diallogShutdownLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        btnDatafile.setText("Xem Đường dẫn Datafile");
        btnDatafile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatafileActionPerformed(evt);
            }
        });

        btnLogfile.setText("Xem Logfile");
        btnLogfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogfileActionPerformed(evt);
            }
        });

        btnInstance.setText("Chi Tiết Liên quan đến instance ");
        btnInstance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstanceActionPerformed(evt);
            }
        });

        btnPGA.setText("Process,PGA_Memor");
        btnPGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPGAActionPerformed(evt);
            }
        });

        btnAlert1.setText("Xem Alert Log");
        btnAlert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlert1ActionPerformed(evt);
            }
        });

        btnSGA.setText("Bộ Nhớ SGA");
        btnSGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSGAActionPerformed(evt);
            }
        });

        btnDatabase.setText("Chi Tiết Liên quan đến database ");
        btnDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatabaseActionPerformed(evt);
            }
        });

        btnDictionary.setText("Xem Dictionary");
        btnDictionary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDictionaryActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Các Thông Số Cơ bản ");

        btnShutdown.setText("Shutdown");
        btnShutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShutdownActionPerformed(evt);
            }
        });

        btnControlfile.setText("Xem Đường dẫn Controlfile");
        btnControlfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlfileActionPerformed(evt);
            }
        });

        btnStartup.setText("Startup");
        btnStartup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartupActionPerformed(evt);
            }
        });

        btnBak.setText("BackupDatabase");
        btnBak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBakActionPerformed(evt);
            }
        });

        btnRes.setText("Restore Database");
        btnRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResActionPerformed(evt);
            }
        });

        btnArchiveLg.setText("Archive_LogMode");
        btnArchiveLg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchiveLgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSystemLayout = new javax.swing.GroupLayout(pnSystem);
        pnSystem.setLayout(pnSystemLayout);
        pnSystemLayout.setHorizontalGroup(
            pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSystemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSystemLayout.createSequentialGroup()
                        .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnControlfile, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnArchiveLg, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDatafile, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnSystemLayout.createSequentialGroup()
                                .addComponent(btnRes, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addGap(219, 219, 219))
                            .addGroup(pnSystemLayout.createSequentialGroup()
                                .addComponent(btnDatabase)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnSystemLayout.createSequentialGroup()
                        .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnSystemLayout.createSequentialGroup()
                                .addComponent(btnDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSGA, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnInstance, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(pnSystemLayout.createSequentialGroup()
                        .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnSystemLayout.createSequentialGroup()
                                .addComponent(btnShutdown, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnStartup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnSystemLayout.createSequentialGroup()
                                .addComponent(btnLogfile, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPGA, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnAlert1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSystemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimebak, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );
        pnSystemLayout.setVerticalGroup(
            pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSystemLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShutdown)
                    .addComponent(btnStartup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlert1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLogfile)
                        .addComponent(btnPGA)))
                .addGap(18, 18, 18)
                .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDictionary)
                    .addComponent(btnSGA)
                    .addComponent(btnInstance))
                .addGap(18, 18, 18)
                .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnControlfile)
                    .addComponent(btnDatafile)
                    .addComponent(btnDatabase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBak)
                    .addComponent(btnRes)
                    .addComponent(btnArchiveLg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimebak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnSystem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSGAActionPerformed
        // TODO add your handling code here:
        dialogSga.show();
         initTableSGA();
    }//GEN-LAST:event_btnSGAActionPerformed

    private void btnPGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPGAActionPerformed
        // TODO add your handling code here:
        dialogPga.show();
        initTablePGA();
    }//GEN-LAST:event_btnPGAActionPerformed

    private void btnInstanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstanceActionPerformed
        // TODO add your handling code here:
        dialogIntance.show();
        initTableInstance();
    }//GEN-LAST:event_btnInstanceActionPerformed

    private void btnDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatabaseActionPerformed
        // TODO add your handling code here:
        dialogData.show();
        initTableDatabase();
    }//GEN-LAST:event_btnDatabaseActionPerformed

    private void btnControlfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlfileActionPerformed
        // TODO add your handling code here:
        dialogControl.show();
        initTableControlFile();
    }//GEN-LAST:event_btnControlfileActionPerformed

    private void btnDatafileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatafileActionPerformed
        // TODO add your handling code here:
        dialoDatafile.show();
        initTableDataFile();
    }//GEN-LAST:event_btnDatafileActionPerformed

    private void btnLogfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogfileActionPerformed
        // TODO add your handling code here:
        dialogLogfile.show();
        initTableLogFile();
    }//GEN-LAST:event_btnLogfileActionPerformed

    private void btnAlert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlert1ActionPerformed
        // TODO add your handling code here:
        diallogAlert.show();
        initTableAlertLog();
    }//GEN-LAST:event_btnAlert1ActionPerformed

    private void btnDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDictionaryActionPerformed
        // TODO add your handling code here:
        dialogDictionary.show();
        initTableDictionary();
    }//GEN-LAST:event_btnDictionaryActionPerformed

    private void btnShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShutdownActionPerformed
        // TODO add your handling code here:
        diallogShutdown.show();
    }//GEN-LAST:event_btnShutdownActionPerformed

    private void btnAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbortActionPerformed
        SQLConnectThrowJDBC provider =new SQLConnectThrowJDBC();
        try {
            
            
            // TODO add your handling code here:
            
            provider.Open(user.getUsername(),user.getPassword(),user.getEnable(),user.getHost(),user.getPort(),user.getSid());
            provider.shutdownAbort();
            provider.Close();
            diallogShutdown.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAbortActionPerformed

    private void btnStartupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartupActionPerformed
        SQLConnectThrowJDBC provider=new SQLConnectThrowJDBC();
        String uName=user.getUsername();
        String uPass=user.getPassword();
        String uHost=user.getHost();
        String uPort=user.getPort();
        String uSid=user.getSid();
       
        String uEnable="false";
        String uEnable_on="true";
        try {
            provider.Open(user.getUsername(),user.getPassword(),uEnable_on,user.getHost(),user.getPort(),user.getSid());
            provider.startup();
            String query=" alter database mount";
            String query1=" alter database open";
            provider.Open(uName,uPass,uEnable,uHost,uPort,uSid);
            provider.executeUpdate(query);
            provider.executeUpdate(query1);
            user.setUsername(uName);
            user.setPassword(uPass);
            user.setEnable(uEnable);
            provider.Close();
        } catch (SQLException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStartupActionPerformed

    private void btnImedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImedActionPerformed
        // TODO add your handling code here:
         SQLConnectThrowJDBC provider =new SQLConnectThrowJDBC();
        try {
            
            
            // TODO add your handling code here:
            
            provider.Open(user.getUsername(),user.getPassword(),user.getEnable(),user.getHost(),user.getPort(),user.getSid());
            provider.shutdownImmed();
            provider.executeUpdate(" alter database close normal");
            provider.executeUpdate(" alter database dismount");
            provider.closeStm();
            System.out.println("Database closed and dismounted");
            provider.shutdownFinal();
            System.out.println("Database stopped");
            diallogShutdown.dispose();
           this.hide();
        } catch (SQLException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnImedActionPerformed

    private void btnTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransActionPerformed
        // TODO add your handling code here:
        SQLConnectThrowJDBC provider =new SQLConnectThrowJDBC();
        try { 
            provider.Open(user.getUsername(),user.getPassword(),user.getEnable(),user.getHost(),user.getPort(),user.getSid());
            provider.shutdownTransc();
            provider.executeUpdate(" alter database close normal");
            provider.executeUpdate(" alter database dismount");
            provider.closeStm();
            System.out.println("Database closed and dismounted");
            provider.shutdownFinal();
            System.out.println("Database stopped");
           
            diallogShutdown.dispose();
            this.hide();
        } catch (SQLException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTransActionPerformed

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        // TODO add your handling code here:
        SQLConnectThrowJDBC provider =new SQLConnectThrowJDBC();
        try { 
            provider.Open(user.getUsername(),user.getPassword(),user.getEnable(),user.getHost(),user.getPort(),user.getSid());
            provider.shutdownNormal();
            provider.executeUpdate(" alter database close normal");
            provider.executeUpdate(" alter database dismount");
            provider.closeStm();
            System.out.println("Database closed and dismounted");
            provider.shutdownFinal();
            System.out.println("Database stopped");
            diallogShutdown.dispose();
            this.hide();
        } catch (SQLException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnBakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBakActionPerformed
        // TODO add your handling code here:
        SQLConnectThrowJDBC provider =new SQLConnectThrowJDBC();
        
       
        
       String [] command={
           "cmd",
       };
       Process p;
        try {
            p=Runtime.getRuntime().exec(command);
            PrintWriter stdin =new PrintWriter(p.getOutputStream());
            stdin.println("RMAN target/@"+user.getSid());
            stdin.println("backup database ; ");
            
            
            stdin.println("exit ");
            stdin.close();
            p.waitFor();
            System.out.println("bak done");
            System.out.println();
            JOptionPane.showMessageDialog(null,"backup database success");
            txtTimebak.setText(new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(Calendar.getInstance().getTime()));
        } catch (IOException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
               
    }//GEN-LAST:event_btnBakActionPerformed

    private void btnResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResActionPerformed
        // TODO add your handling code here:
        SQLConnectThrowJDBC provider =new SQLConnectThrowJDBC();
         String uName=user.getUsername();
        String uPass=user.getPassword();
        String uHost=user.getHost();
        String uPort=user.getPort();
        String uSid=user.getSid();
        String uEnable="false";
       String [] command={
           "cmd",
       };
       Process p;
        try {
           
            
            provider.Open(user.getUsername(),user.getPassword(),user.getEnable(),user.getHost(),user.getPort(),user.getSid());
            provider.shutdownImmed();
            provider.executeUpdate(" alter database close normal");
            provider.executeUpdate(" alter database dismount");
            provider.closeStm();
            
            System.out.println("Database closed and dismounted");
            provider.shutdownFinal();
            System.out.println("Database stopped");
            provider.Open(uName,uPass,"true",uHost,uPort,uSid);
            provider.startup();
            String query=" alter database mount";
            provider.Open(uName,uPass,"false",uHost,uPort,uSid);
            provider.executeUpdate(query);
            System.out.println("Database mounted");
            provider.Close();
             p=Runtime.getRuntime().exec(command);
            PrintWriter stdin =new PrintWriter(p.getOutputStream());
            stdin.println("RMAN target/@"+user.getSid());
            stdin.println("restore database ; ");
            System.out.println("restored");
            stdin.println(" recover database until time \"to_date ('"+txtTimebak.getText()+"',\n" +
                "'DD/MM/YYYY HH24:MI:SS')\"; ");
             System.out.println("recovered");
             // can chu y lai khi set archivelog
            stdin.println("alter database open resetlogs;");
            stdin.println("exit ");
            stdin.close();
            p.waitFor();
            JOptionPane.showMessageDialog(this,"restore suscess");
        } catch (IOException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
               
        
    }//GEN-LAST:event_btnResActionPerformed

    private void btnArchiveLgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchiveLgActionPerformed

        SQLConnectThrowJDBC provider=new SQLConnectThrowJDBC();
            String uName=user.getUsername();
            String uPass=user.getPassword();
            String uHost=user.getHost();
            String uPort=user.getPort();
            String uSid=user.getSid();
            String uEnable="false";
         String [] command={
           "cmd",
       };
          Process p;
        try {
            p=Runtime.getRuntime().exec(command);
            PrintWriter stdin =new PrintWriter(p.getOutputStream());
            stdin.println("sqlplus"+uName+"/"+uPass+"@"+uSid+ " as sysdba");
            stdin.println("shutdown immediate");
            stdin.println("startup mount");
            System.out.println("database mounted");
            stdin.println("aler database archivelog");
            stdin.println("alter database open");
            stdin.println("alter system switch logfile;");
            stdin.println("exit ");
            stdin.close();
                p.waitFor();
        } catch (IOException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_btnArchiveLgActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        DAO_PGA daopga=new DAO_PGA();
        try {
            daopga.alterPga(txtNamepga.getText(),txtValue.getText());
              JOptionPane.showMessageDialog(null,"Edit thành công");
        } catch (SQLException ex) {
            Logger.getLogger(GUI_InfoOracle.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
            return;
        }
        tblModelPga= new TableModelPGA();
        tblPga.setModel(tblModelPga);
        
    }//GEN-LAST:event_btnEditActionPerformed
    public void initTableSGA(){
        tblModelSga= new TableModelSGA();
        tblSGA1.setModel(tblModelSga);
        tblSGA1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()){
                        return;
                }
                int index=tblSGA1.getSelectedRow();
                if (index <0){
                    return ;
                }
            }
        });
    }
    public void initTablePGA() {
        tblModelPga= new TableModelPGA();
        tblPga.setModel(tblModelPga);
        tblPga.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()){
                        return;
                }
                int index=tblPga.getSelectedRow();
                if (index <0){
                    return ;
                }
                POJO_PGA popga=tblModelPga.getByIndex(index);
                txtNamepga.setText(popga.getName());
                txtValue.setText(popga.getValue());
            }
        });
    }
    public void initTableInstance() {
        tblModelInstance= new TableModelInstance();
        tblInstance.setModel(tblModelInstance);
        tblInstance.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()){
                        return;
                }
                int index=tblInstance.getSelectedRow();
                if (index <0){
                    return ;
                }
            }
        });
    }
    public void initTableDatabase() {
        tblModelDatabase= new TableModelDatabase();
        tblDatabase.setModel(tblModelDatabase);
        tblDatabase.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()){
                        return;
                }
                int index=tblDatabase.getSelectedRow();
                if (index <0){
                    return ;
                }
            }
        });
    }
    public void initTableControlFile()
    {
        tblModelControlfile = new TableModeControlfile();
        tblControlfile.setModel(tblModelControlfile);
        tblControlfile.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()){
                        return;
                }
                int index=tblControlfile.getSelectedRow();
                if (index <0){
                    return ;
                }
            }
        });
    }
    public void initTableDataFile()
    {
        tblModelDatafile = new TableModelDatafile();
        tblDatafile.setModel(tblModelDatafile);
        tblDatafile.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()){
                        return;
                }
                int index=tblDatafile.getSelectedRow();
                if (index <0){
                    return ;
                }
            }
        });
    }
    public void initTableLogFile()
    {
        tblModelLogfile = new TableModelLogfile();
        tblLogfile.setModel(tblModelLogfile);
        tblLogfile.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()){
                        return;
                }
                int index=tblLogfile.getSelectedRow();
                if (index <0){
                    return ;
                }
            }
        });
    }
    public void initTableAlertLog()
    {
        tblModelAlertlog = new TableModeAlertLog();
        tblAlert.setModel(tblModelAlertlog);
        tblAlert.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()){
                        return;
                }
                int index=tblAlert.getSelectedRow();
                if (index <0){
                    return ;
                }
            }
        
        });
    }
     public void initTableDictionary()
    {
        tblModelDictionary = new TableModeDictionary();
        tblDictionary.setModel(tblModelDictionary);
        tblDictionary.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()){
                        return;
                }
                int index=tblDictionary.getSelectedRow();
                if (index <0){
                    return ;
                }
            }
        
        });
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbort;
    private javax.swing.JButton btnAlert1;
    private javax.swing.JButton btnArchiveLg;
    private javax.swing.JButton btnBak;
    private javax.swing.JButton btnControlfile;
    private javax.swing.JButton btnDatabase;
    private javax.swing.JButton btnDatafile;
    private javax.swing.JButton btnDictionary;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnImed;
    private javax.swing.JButton btnInstance;
    private javax.swing.JButton btnLogfile;
    private javax.swing.JButton btnNormal;
    private javax.swing.JButton btnPGA;
    private javax.swing.JButton btnRes;
    private javax.swing.JButton btnSGA;
    private javax.swing.JButton btnShutdown;
    private javax.swing.JButton btnStartup;
    private javax.swing.JButton btnTrans;
    private javax.swing.JDialog diallogAlert;
    private javax.swing.JDialog diallogShutdown;
    private javax.swing.JDialog dialoDatafile;
    private javax.swing.JDialog dialogControl;
    private javax.swing.JDialog dialogData;
    private javax.swing.JDialog dialogDictionary;
    private javax.swing.JDialog dialogIntance;
    private javax.swing.JDialog dialogLogfile;
    private javax.swing.JDialog dialogPga;
    private javax.swing.JDialog dialogSga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel pnSystem;
    private javax.swing.JTable tblAlert;
    private javax.swing.JTable tblControlfile;
    private javax.swing.JTable tblDatabase;
    private javax.swing.JTable tblDatafile;
    private javax.swing.JTable tblDictionary;
    private javax.swing.JTable tblInstance;
    private javax.swing.JTable tblLogfile;
    private javax.swing.JTable tblPga;
    private javax.swing.JTable tblSGA1;
    private javax.swing.JTextField txtNamepga;
    private javax.swing.JTextField txtTimebak;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
