/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import POJO.POJO_User;
import SqlServerProvider.SQLConnectThrowJDBC;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author trung
 */
public class MainGui extends javax.swing.JFrame {
        private JPanel childPanel;
        POJO_User u=new POJO_User();
    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
         SQLConnectThrowJDBC provider=new SQLConnectThrowJDBC();
            
        lblUser.setText(u.getUsername());
        if (!u.getUsername().trim().equals("sys as sysdba"))
        {
            btnSys.setEnabled(false);
            btnInfoUser.setEnabled(false);
            btnRoles.setEnabled(false);
            btnProfiles.setEnabled(false);
            btnDetailtbl.setEnabled(false);
            btnSes.setEnabled(false);
        }
        else 
        {
            btnSys.setEnabled(true);
            btnInfoUser.setEnabled(true);
            btnDetailtbl.setEnabled(true);
            btnRoles.setEnabled(true);
            btnProfiles.setEnabled(true);
            btnSes.setEnabled(true);
        }
            try {
                provider.Open(u.getUsername(), u.getPassword(),u.getEnable(),u.getHost(),u.getPort(),u.getSid());
                String user_sys=("select to_char(last_login,'DD/MM/YYYY hh24:MI:SS') from dba_users where username ='SYSTEM'");
                String ses_sys=String.format(" select to_char(LOGON_TIME,'DD/MM/YYYY hh24:MI:SS') from v$session where type!='BACKGROUND' and username='SYS'");
                String dba_user=String.format("select to_char(last_login,'DD/MM/YYYY hh24:MI:SS ') from dba_users where username =UPPER('%s')",u.getUsername());
                String ses=String.format(" select to_char(LOGON_TIME,'DD/MM/YYYY hh24:MI:SS') from v$session where type!='BACKGROUND' and username=UPPER('%s')",u.getUsername());
                ResultSet rs1;
                ResultSet rs2;
               
               
                if(u.getUsername().equals("sys as sysdba"))
                {
                     rs1=provider.executeQuery(user_sys);
                     while (rs1.next())
                     {
                         txtLastlogin.setText(rs1.getString(1));
                     }
                     rs2=provider.executeQuery(ses_sys);
                     while (rs2.next())
                     {
                         txtLogin.setText(rs2.getString(1));
                     }
                }
                else
                {
                    rs1=provider.executeQuery(dba_user);
                    while (rs1.next())
                     {
                         txtLastlogin.setText(rs1.getString(1));
                     }
                    rs2=provider.executeQuery(ses);
                    while (rs2.next())
                     {
                         txtLogin.setText(rs2.getString(1));
                     }
                }
                provider.Close();
               
            } catch (SQLException ex) {
                Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lblUser = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        btnSys = new javax.swing.JButton();
        btnProfiles = new javax.swing.JButton();
        btnDetailtbl = new javax.swing.JButton();
        btnRoles = new javax.swing.JButton();
        btnInfoUser = new javax.swing.JButton();
        btnSes = new javax.swing.JButton();
        btnAudit = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtLastlogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jToolBar1.setRollover(true);

        lblUser.setText("jLabel1");
        jToolBar1.add(lblUser);

        jToolBar2.setRollover(true);
        jToolBar1.add(jToolBar2);

        btnSys.setText("Hệ Thống");
        btnSys.setFocusable(false);
        btnSys.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSysActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSys);

        btnProfiles.setText("Profiles");
        btnProfiles.setFocusable(false);
        btnProfiles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProfiles.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProfiles);

        btnDetailtbl.setText("Chi Tiết Tablespace");
        btnDetailtbl.setFocusable(false);
        btnDetailtbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetailtbl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDetailtbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailtblActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDetailtbl);

        btnRoles.setText("Roles");
        btnRoles.setFocusable(false);
        btnRoles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRoles.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRoles);

        btnInfoUser.setText("User_Info");
        btnInfoUser.setFocusable(false);
        btnInfoUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfoUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInfoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoUserActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInfoUser);

        btnSes.setText("Session_info");
        btnSes.setFocusable(false);
        btnSes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSes);

        btnAudit.setText("Audit_FGA");
        btnAudit.setFocusable(false);
        btnAudit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAudit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAudit);

        pnMain.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(""), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 153, 0))));
        pnMain.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Logon_time:");

        jLabel2.setText("Last_login:");

        txtLogin.setToolTipText("");
        txtLogin.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        txtLogin.setEnabled(false);

        txtLastlogin.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txtLastlogin.setEnabled(false);
        txtLastlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLogin)
                            .addComponent(txtLastlogin))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSysActionPerformed
        showPannel(new GUI_InfoOracle());
    }//GEN-LAST:event_btnSysActionPerformed

    private void btnDetailtblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailtblActionPerformed
        showPannel(new GUI_Moredetail_Tablespace());
    }//GEN-LAST:event_btnDetailtblActionPerformed

    private void btnProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilesActionPerformed
        // TODO add your handling code here:
        showPannel(new GUI_Profiles());
    }//GEN-LAST:event_btnProfilesActionPerformed

    private void btnRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolesActionPerformed
        // TODO add your handling code here:
        showPannel(new GUI_Roles());
    }//GEN-LAST:event_btnRolesActionPerformed

    private void btnInfoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoUserActionPerformed
        // TODO add your handling code here:
        showPannel(new GUI_User());
    }//GEN-LAST:event_btnInfoUserActionPerformed

    private void btnSesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesActionPerformed
        showPannel(new GUI_Session());
    }//GEN-LAST:event_btnSesActionPerformed

    private void txtLastloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastloginActionPerformed

    private void btnAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditActionPerformed
        // TODO add your handling code here:
        showPannel(new GUI_AUDIT_POLICIES());
    }//GEN-LAST:event_btnAuditActionPerformed
    private void showPannel(JPanel panel)
    {
        childPanel =panel;
        pnMain.removeAll();
        pnMain.add(childPanel);
        pnMain.validate();
             
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainGui main=new MainGui();
                main.setVisible(true);
                main.setLocationRelativeTo(null); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAudit;
    private javax.swing.JButton btnDetailtbl;
    private javax.swing.JButton btnInfoUser;
    private javax.swing.JButton btnProfiles;
    private javax.swing.JButton btnRoles;
    private javax.swing.JButton btnSes;
    private javax.swing.JButton btnSys;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTextField txtLastlogin;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
